// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TinPhongCompany
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Create a new door item")]
    public partial class CreateANewDoorItemFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AddDoor.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Create a new door item", "  In order to add new door to db\r\n  As a site administrator\r\n  I want to be able " +
                    "to create, view and manage door item records", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
  #line 7
  testRunner.Given("I am logged into the site as an administrator", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a new door item record with full data")]
        public virtual void CreateANewDoorItemRecordWithFullData()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a new door item record with full data", ((string[])(null)));
#line 9
this.ScenarioSetup(scenarioInfo);
#line 6
  this.FeatureBackground();
#line 10
  testRunner.When("I go to page add product", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "MetaTitle",
                        "SeoTitle",
                        "Code",
                        "Description",
                        "Image",
                        "Price",
                        "PromotionPrice",
                        "CategoryID",
                        "ProductDetail",
                        "Waranty",
                        "MetaKeywords",
                        "MetaDescriptions",
                        "Status",
                        "ViewCount"});
            table1.AddRow(new string[] {
                        "Cửa đi KINGLONG 2 cánh trượt",
                        "Cửa đi KINGLONG 2 cánh trượt",
                        "Cửa đi KINGLONG 2 cánh trượt tại TPHCM",
                        "KL001",
                        "Cửa đi KINGLONG 2 cánh trượt , chất lượng cao",
                        "/Assets/Images/logo.jpg",
                        "1900000",
                        "1890000",
                        "1",
                        "Cửa đi KINGLONG 2 cánh trượt , chất lượng cao",
                        "12",
                        "Cửa đi KINGLONG 2 cánh trượt",
                        "Cửa đi KINGLONG 2 cánh trượt tại TPHCM, quận 10, quận Thủ đức, Bình Thạnh",
                        "true",
                        "1000"});
#line 11
  testRunner.And("I enter the following information", ((string)(null)), table1, "And ");
#line 14
  testRunner.And("I click the \"Thêm\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
  testRunner.Then("I should see page view  \"Danh Sách Sản Phẩm\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a new door item record with empty name door")]
        public virtual void CreateANewDoorItemRecordWithEmptyNameDoor()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a new door item record with empty name door", ((string[])(null)));
#line 17
 this.ScenarioSetup(scenarioInfo);
#line 6
  this.FeatureBackground();
#line 18
  testRunner.When("I go to page add product", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "MetaTitle",
                        "SeoTitle",
                        "Code",
                        "Description",
                        "Image",
                        "Price",
                        "PromotionPrice",
                        "CategoryID",
                        "ProductDetail",
                        "Waranty",
                        "MetaKeywords",
                        "MetaDescriptions",
                        "Status",
                        "ViewCount"});
            table2.AddRow(new string[] {
                        "Cửa đi KINGLONG 2 cánh trượt",
                        "Cửa đi KINGLONG 2 cánh trượt tại TPHCM",
                        "KL001",
                        "Cửa đi KINGLONG 2 cánh trượt , chất lượng cao",
                        "/Assets/Images/logo.jpg",
                        "1900000",
                        "1890000",
                        "1",
                        "Cửa đi KINGLONG 2 cánh trượt , chất lượng cao",
                        "12",
                        "Cửa đi KINGLONG 2 cánh trượt",
                        "Cửa đi KINGLONG 2 cánh trượt tại TPHCM, quận 10, quận Thủ đức, Bình Thạnh",
                        "true",
                        "1000"});
#line 19
  testRunner.And("I enter the following information with empty name door", ((string)(null)), table2, "And ");
#line 22
  testRunner.And("I click the \"Thêm\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
  testRunner.Then("I should see page view \"Thêm Sản Phẩm\" again", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a new door item record with price<0")]
        public virtual void CreateANewDoorItemRecordWithPrice0()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a new door item record with price<0", ((string[])(null)));
#line 25
this.ScenarioSetup(scenarioInfo);
#line 6
  this.FeatureBackground();
#line 26
  testRunner.When("I go to page add product", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "MetaTitle",
                        "SeoTitle",
                        "Code",
                        "Description",
                        "Image",
                        "Price",
                        "PromotionPrice",
                        "CategoryID",
                        "ProductDetail",
                        "Waranty",
                        "MetaKeywords",
                        "MetaDescriptions",
                        "Status",
                        "ViewCount"});
            table3.AddRow(new string[] {
                        "Cửa đi KINGLONG 2 cánh trượt",
                        "Cửa đi KINGLONG 2 cánh trượt",
                        "Cửa đi KINGLONG 2 cánh trượt tại TPHCM",
                        "KL001",
                        "Cửa đi KINGLONG 2 cánh trượt , chất lượng cao",
                        "/Assets/Images/logo.jpg",
                        "-1000000",
                        "1890000",
                        "1",
                        "Cửa đi KINGLONG 2 cánh trượt , chất lượng cao",
                        "12",
                        "Cửa đi KINGLONG 2 cánh trượt",
                        "Cửa đi KINGLONG 2 cánh trượt tại TPHCM, quận 10, quận Thủ đức, Bình Thạnh",
                        "true",
                        "1000"});
#line 27
  testRunner.And("I enter the following information with price<0", ((string)(null)), table3, "And ");
#line 30
  testRunner.And("I click the \"Thêm\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
  testRunner.Then("I should see page view \"Thêm Sản Phẩm\" again because error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a new door item record with viewcount<0")]
        public virtual void CreateANewDoorItemRecordWithViewcount0()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a new door item record with viewcount<0", ((string[])(null)));
#line 33
this.ScenarioSetup(scenarioInfo);
#line 6
  this.FeatureBackground();
#line 34
  testRunner.When("I go to page add product", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "MetaTitle",
                        "SeoTitle",
                        "Code",
                        "Description",
                        "Image",
                        "Price",
                        "PromotionPrice",
                        "CategoryID",
                        "ProductDetail",
                        "Waranty",
                        "MetaKeywords",
                        "MetaDescriptions",
                        "Status",
                        "ViewCount"});
            table4.AddRow(new string[] {
                        "Cửa đi KINGLONG 2 cánh trượt",
                        "Cửa đi KINGLONG 2 cánh trượt",
                        "Cửa đi KINGLONG 2 cánh trượt tại TPHCM",
                        "KL001",
                        "Cửa đi KINGLONG 2 cánh trượt , chất lượng cao",
                        "/Assets/Images/logo.jpg",
                        "1000000",
                        "1890000",
                        "1",
                        "Cửa đi KINGLONG 2 cánh trượt , chất lượng cao",
                        "12",
                        "Cửa đi KINGLONG 2 cánh trượt",
                        "Cửa đi KINGLONG 2 cánh trượt tại TPHCM, quận 10, quận Thủ đức, Bình Thạnh",
                        "true",
                        "-1000"});
#line 35
  testRunner.And("I enter the following information with viewcount<0", ((string)(null)), table4, "And ");
#line 38
  testRunner.And("I click the \"Thêm\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
  testRunner.Then("I should see page view \"Thêm Sản Phẩm\" again because error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a new door item record with empty image field")]
        public virtual void CreateANewDoorItemRecordWithEmptyImageField()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a new door item record with empty image field", ((string[])(null)));
#line 41
this.ScenarioSetup(scenarioInfo);
#line 6
  this.FeatureBackground();
#line 42
  testRunner.When("I go to page add product", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "MetaTitle",
                        "SeoTitle",
                        "Code",
                        "Description",
                        "Price",
                        "PromotionPrice",
                        "CategoryID",
                        "ProductDetail",
                        "Waranty",
                        "MetaKeywords",
                        "MetaDescriptions",
                        "Status",
                        "ViewCount"});
            table5.AddRow(new string[] {
                        "Cửa đi KINGLONG 2 cánh trượt",
                        "Cửa đi KINGLONG 2 cánh trượt",
                        "Cửa đi KINGLONG 2 cánh trượt tại TPHCM",
                        "KL001",
                        "Cửa đi KINGLONG 2 cánh trượt , chất lượng cao",
                        "1000000",
                        "1890000",
                        "1",
                        "Cửa đi KINGLONG 2 cánh trượt , chất lượng cao",
                        "12",
                        "Cửa đi KINGLONG 2 cánh trượt",
                        "Cửa đi KINGLONG 2 cánh trượt tại TPHCM, quận 10, quận Thủ đức, Bình Thạnh",
                        "true",
                        "1000"});
#line 43
  testRunner.And("I enter the following information with empty image field", ((string)(null)), table5, "And ");
#line 46
  testRunner.And("I click the \"Thêm\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
  testRunner.Then("I should see page view \"Thêm Sản Phẩm\" again because error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
